name: Lint and Test

on:
  push:
    branches: [ main ]
    tags: [ v* ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repo
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.19

    - name: Lint
      uses: golangci/golangci-lint-action@v3
      with:
        skip-pkg-cache: true

    - name: Run Tests
      run: make test